[package]
name = "polkadot-network"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot-specific networking protocol"

[dependencies]
substrate-network = { path = "../../substrate/network" }
