[package]
name = "substrate-consensus-trk"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Time-based round Robin King consensus-algorithm for substrate"

[dependencies]
futures = "0.1.17"
parity-codec = { version = "1.1" }
substrate-primitives = { path = "../../primitives" }
srml-support = { path = "../../../srml/support" }
sr-primitives = { path = "../../sr-primitives" }
sr-version = { path = "../../sr-version" }
tokio = "0.1.7"
parking_lot = "0.4"
error-chain = "0.12"
log = "0.3"

[dev-dependencies]
substrate-keyring = { path = "../../keyring" }
substrate-executor = { path = "../../executor" }
