# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: rust
matrix:
  fast_finish: true

  include:
    - name: "Webassembly on nightly"
      rust: nightly
      env: TARGET=wasm
    - name: "Latest stable native"
      rust: stable
      env: TARGET=native

cache: cargo

env:
  - RUST_BACKTRACE=1

branches:
  only:
  - master

before_install:
  # Check how much space we've got on this machine.
  - df -h

install:
  # pull dependencies
  - travis_wait 30 cargo update

script:
  - ./ci/script.sh

after_script:
  # Check how much free disk space left after the build
  - df -h
