[package]
name = "demo-network"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate demo networking protocol"

[dependencies]
parking_lot = "0.4"
demo-api = { path = "../api" }
demo-consensus = { path = "../consensus" }
demo-primitives = { path = "../primitives" }
substrate-bft = { path = "../../substrate/bft" }
substrate-network = { path = "../../substrate/network" }
substrate-primitives = { path = "../../substrate/primitives" }
ed25519 = { path = "../../substrate/ed25519" }
futures = "0.1"
tokio = "0.1.7"
log = "0.4"
rhododendron = "0.3"
