[package]
name = "substrate-state-machine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate State Machine"

[dependencies]
byteorder = "1.1"
ethereum-types = "0.3"
hex-literal = "0.1.0"
log = "0.3"
parking_lot = "0.4"
triehash = "0.1"

substrate-primitives = { path = "../primitives", version = "0.1.0" }

hashdb = { git = "https://github.com/paritytech/parity.git", rev = "202c54d42398fc4b49d67ffbf9070522e38f9360" }
memorydb = { git = "https://github.com/paritytech/parity.git", rev = "202c54d42398fc4b49d67ffbf9070522e38f9360" }
patricia-trie = { git = "https://github.com/paritytech/parity.git", rev = "202c54d42398fc4b49d67ffbf9070522e38f9360" }
