[package]
name = "substrate-finality-grandpa"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
finality-grandpa = "0.1"
futures = "0.1.17"
parity-codec = "2.0"
sr-primitives = { path = "../sr-primitives" }
substrate-primitives = { path = "../primitives" }
substrate-client = { path = "../client" }
log = "0.4"
