[package]
name = "sr-io"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
sr-std = { path = "../sr-std", default_features = false }
environmental = { version = "~1.0", optional = true }
substrate-state-machine = { path = "../state-machine", optional = true }
substrate-primitives = { path = "../primitives", default_features = false }
parity-codec = { version = "2.0", default_features = false }
hash-db = { git = "https://github.com/paritytech/trie", default_features = false }
substrate-trie = { path = "../trie", optional = true }

[features]
default = ["std"]
std = [
	"environmental",
	"substrate-state-machine",
	"substrate-primitives/std",
	"parity-codec/std",
	"hash-db/std",
	"sr-std/std",
	"substrate-trie"
]
nightly = []
strict = []
